import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from './Components/Header'
import Footer from './Components/Footer'
import { Providers } from './provider'
const inter = Inter({ subsets: ['latin'] })
export const revalidate = 10

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} dark:bg-slate-800`} >
        <Providers>
        <Header />
        {children}
        <Footer/>

        </Providers>
        </body>
    </html>
  )
}
